name: Create and Upload Artifact

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy SBOM to Working Directory
      run: |
        cp ./some-sboms/kube-addon-manager-v9.1.1.sha256-c0ed56727cd78700034f2f863d774412c78681fb6535456f5e5c420f4248c5a1.syft.0.58.0.spdx.json sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
