name: Create and Upload Artifact

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create text file
      run: echo "Hello, World!" > output.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output.txt

    - name: Create another text file
      run: echo "Hello, again!" > output2.txt

    - name: Upload another artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-file-2
        path: output2.txt